#!/usr/bin/env bash
# Auto-generated by matugen — do not edit directly
PRIMARY_LIGHT="#85468c"
PRIMARY_DARK="#f8adfb"
SECONDARY_LIGHT="#7c4e7f"
SECONDARY_DARK="#ecb5ec"
TERTIARY_LIGHT="#904a4b"
TERTIARY_DARK="#ffb3b2"
