#!/usr/bin/env bash
# Auto-generated by matugen — do not edit directly
PRIMARY_LIGHT="#536068"
PRIMARY_DARK="#bbc8d2"
SECONDARY_LIGHT="#585f64"
SECONDARY_DARK="#c0c7cd"
TERTIARY_LIGHT="#4e616c"
TERTIARY_DARK="#b5c9d7"
